[2024-09-26 22:27:59,545] INFO _log() L97    * Restarting with stat - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:28:01,305] ERROR log_exception() L838  Exception on /pedidos [GET] - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\app.py", line 358, in get_pedidos
    pedidos = session.query(Pedidos).all()
                            ^^^^^^^
NameError: name 'Pedidos' is not defined. Did you mean: 'Pedido'?
[2024-09-26 22:28:01,309] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:28:01] "[35m[1mGET /pedidos HTTP/1.1[0m" 500 - - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:28:07,540] ERROR log_exception() L838  Exception on /pedidos [GET] - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\app.py", line 358, in get_pedidos
    pedidos = session.query(Pedidos).all()
                            ^^^^^^^
NameError: name 'Pedidos' is not defined. Did you mean: 'Pedido'?
[2024-09-26 22:28:07,543] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:28:07] "[35m[1mGET /pedidos HTTP/1.1[0m" 500 - - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:28:12,342] INFO _log() L97    * Detected change in 'C:\\Projetos\\API-Doces-Simplificada\\app.py', reloading - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:28:12,547] INFO _log() L97    * Restarting with stat - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:28:14,383] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:28:14] "GET /pedidos HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:28:34,458] ERROR log_exception() L838  Exception on /pedido [DELETE] - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\app.py", line 376, in del_pedido
    pedido_nome = query.nome
                  ^^^^^^^^^^
  File "C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'PedidoBuscaSchema' object has no attribute 'nome'
[2024-09-26 22:28:34,462] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:28:34] "[35m[1mDELETE /pedido?id=3 HTTP/1.1[0m" 500 - - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:30:20,791] INFO _log() L97    * Detected change in 'C:\\Projetos\\API-Doces-Simplificada\\app.py', reloading - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:30:20,967] INFO _log() L97    * Restarting with stat - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:30:22,719] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:30:22] "DELETE /pedido?id=3 HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-26 22:30:33,579] INFO _log() L97   127.0.0.1 - - [26/Sep/2024 22:30:33] "GET /pedidos HTTP/1.1" 200 - - call_trace=C:\Projetos\API-Doces-Simplificada\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-09-27 01:31:06,888] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000 - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:06,891] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:06,893] INFO _log() L97    * Restarting with stat - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,441] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,452] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,462] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "GET /openapi/ HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,526] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,526] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,527] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
[2024-09-27 01:31:38,544] INFO _log() L97   172.18.0.1 - - [27/Sep/2024 01:31:38] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L97  
